# -*- coding: utf-8 -*-
"""Cópia de Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SmS1yIOXoChl_D_itpzjikIFb6nQPNR

#entrada das dimensões do reservatorio em centimetros
"""

altura = float(input("digite a altura do reservatório(cm):"))
largura = float(input("digite a largura do reservatório(cm):"))
comprimento = float(input("digite o comprimento do reservatório(cm):"))

"""#entrada so consumo diario em litros

"""

consumo_diario = float(input("digite o consumo medio diario (litros/dia):"))

"""calculo do volume em cm³ e depois a conversão para litros"""

volume_cm3 = altura*largura*comprimento
capacidade_litros = volume_cm3/1000 #1000cm³ = 1 litro

"""#calculo da autonomia em dias"""

autonomia_dias = capacidade_litros/ consumo_diario

"""# classificaçao do consumo"""

if autonomia_dias <2:
  classificacao = "consumo elevado"
elif 2<=autonomia_dias<=7:
  classificacao = "consumo moderado"
else:
  classificacao = "consumo reduzido"

"""# saida dos resultados"""

print("\nRESULTADOS:")
print(f"capacidade total do reservatorio:{capacidade_litros:.2f}litros")
print(f"autonomia do reservatorio:{autonomia_dias:.2f}dias")
print(f"classificacao do consumo:{classificacao}")