# -*- coding: utf-8 -*-
"""Cópia de Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DiQDnLoae1E_2ctcjLT4itZ7D08LZ1g
"""

import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

nome_arquivo_csv = 'preco_automoveis.csv'

def gerar_dados_automoveis(num_linha):
  dados=[]
  for _ in range(num_linha):
    codigo_automoveis = random.randint(1000,9999)
    marcas = f"marcas{random.choice(['chevolet','fiat','volkswagen','ford'])}, {random.randint(1,1000)}"
    modelo = random.choice(['gol','corsa','palio','uno','fordKA'])
    cor = random.choice(['azul','prata','verde','preto','branco'])
    ano = random.randint(1994,2025)
    portas = random.randint(2,4)
    km = round(random.uniform(1000,1000000),2)
    preco = round (random.uniform(10000,100000),2)
    dados.append([codigo_automoveis,marcas,modelo,cor,ano,portas,km,preco])
  return dados

Dados_automoveis = gerar_dados_automoveis(10000)

cabecalho = ['codigo_automoveis','marcas','modelo','cor','ano','portas','km','preco']
df = pd.DataFrame(Dados_automoveis,columns=cabecalho)
df.to_csv(nome_arquivo_csv, index = False)

df = pd.read_csv(nome_arquivo_csv)

print(df.describe())

print(df.info())

preco_mean = df['preco'].mean()

preco_mean

preco_std = df['preco'].std()

preco_min = df['preco'].min()

preco_max = df['preco'].max()

print(f'Média de preço: {preco_mean}')
print(f'desvio de preço: {preco_std}')
print(f'min de preço: {preco_min}')
print(f'Max de preço: {preco_max}')

plt.figure(figsize=(10, 6))
sns.histplot(df['preco'],kde =True )
plt.title('Distribuição dos Preços dos automoveis')
plt.xlabel('Preço')
plt.ylabel('frequencia')
plt.show()

preco_por_marcas = df.groupby('marcas')['preco'].agg(['mean','std']).reset_index()
print(preco_por_marcas)

automoveis_mais_caros = preco_por_marcas.sort_values (by='mean', ascending=False)
print('automoveis com a media mais cara')
print (automoveis_mais_caros)

df['preco_modelo'] = df['preco']/df['km']
preco_m2_por_bairro = df.groupby('marcas') ['preco_modelo'].mean().reset_index()
bairros_mais_valorizados = preco_m2_por_bairro.sort_values(by='preco_modelo', ascending=False)
print('Precos mais altos por modelo')
print(automoveis_mais_caros)

plt.figure(figsize=(7,3.5))
sns.boxplot(x='modelo',y='preco', data=df)
plt.title('distribuição estados')
plt.xlabel('modelo')
plt.ylabel('preco')
plt.show()