# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFOL6z3iUqm_dGF5V2Y8VRfY2hmBg3xg

# leitura de um arquivo e análise de dados
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

"""# definir o nome do arquivo csv

"""

nome_aquivo_csv = 'precos_imveis.csv'

def gerar_dados_imoveis(num_linha):
    dados =[]
    for _ in range(num_linha):
      codigo_imovel = random.randint(1000,9999)
      endereco = f"Rua {random.choice(['A','B','C'])}, {random.randint(1,100)}"
      bairro = random.choice(['centro','vila','bairro novo'])
      tipo_imovel = random.choice(['casa','apartamento', 'sobrado'])
      area_total = round(random.uniform(50, 300),2)
      quartos= random.randint(1,5)
      banheiros= random.randint(1,3)
      vagas_garagem = random.randint(0,2)
      ano_construcao= random.randint(1980,2025)
      preco = round (random.uniform(100000,1000000),2)
      dados.append([codigo_imovel, endereco,bairro,tipo_imovel,area_total,quartos,banheiros,vagas_garagem,ano_construcao,preco])
    return dados

dados_imoveis = gerar_dados_imoveis(10000)

#Dados no arquivo csv

cabecalho = ['codigo_imovel','endereco','bairro','tipo_imovel','area_total','quartos','banheiros','vagas_garagem','ano_construcao','preco']
df = pd.DataFrame(dados_imoveis,columns=cabecalho)
df.to_csv(nome_aquivo_csv, index = False)

df = pd.read_csv(nome_aquivo_csv)

print(df.describe())

print(df.info())

preco_mean = df['preco'].mean()

preco_mean

preco_std = df['preco'].std()

preco_min = df['preco'].min()

preco_max = df['preco'].max()

print(f'Média de preço: {preco_mean}')
print(f'desvio de preço: {preco_std}')
print(f'min de preço: {preco_min}')
print(f'Max de preço: {preco_max}')

plt.figure(figsize=(10, 6))
sns.histplot(df['preco'],kde =True )
plt.title('Distribuição dos Preços dos imoveis')
plt.xlabel('Preço')
plt.ylabel('frequencia')
plt.show()

preco_por_bairro = df.groupby('bairro')['preco'].agg(['mean','std']).reset_index()
print(preco_por_bairro)

#Areas valorizadas
bairros_mais_caros = preco_por_bairro.sort_values (by='mean', ascending=False)
print('Bairro com os médios mais altos')
print (bairros_mais_caros)

# preco metro quadrado
df['preco_m2'] = df['preco']/df['area_total']
preco_m2_por_bairro = df.groupby('bairro') ['preco_m2'].mean().reset_index()
bairros_mais_valorizados = preco_m2_por_bairro.sort_values(by='preco_m2', ascending=False)
print('Precos mais altos por metro quadrado')
print(bairros_mais_valorizados)

plt.figure(figsize=(14,7))
sns.boxplot(x='bairro',y='preco', data=df)
plt.title('distribuição por bairro')
plt.xlabel('bairro')
plt.ylabel('preco')
plt.show()