# -*- coding: utf-8 -*-
"""Cópia de Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XsQlANn5MxpivDXLbiSG0JFN0NtQ-xW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.feature_extraction.text import TfidfTransformer , TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
import random as rd

nome_arquivo_csv = 'dados_clientes.csv'

def gerar_nome_aquivo(num_linha):
  dados=[]
  for _ in range (num_linha):
    tempo_de_contrato = rd.randint(1000,9999)
    suporte_tecnico = rd.choice(['eletrica','mecanica','automação','eletronica'])
    valor_da_fatura = round(rd.uniform(1000,1000000),2)
    preco = round (rd.uniform(10000,100000),2)
    dados.append([tempo_de_contrato,suporte_tecnico,valor_da_fatura,preco])
  return dados

dados_clientes = gerar_nome_aquivo(10000)

cabecalho = ['tempo_de_contrato','suporte_tecnico','valor_da_fatura','preco']
df = pd.DataFrame(dados_clientes,columns=cabecalho)
df.to_csv(nome_arquivo_csv, index = False)

df = pd.read_csv(nome_arquivo_csv)

print(df.describe())

print(df.info())

preco_mean = df['valor_da_fatura'].mean()

preco_std = df['valor_da_fatura'].std()

preco_min = df['valor_da_fatura'].min()

preco_max = df['valor_da_fatura'].max()

print(f'Média de preço: {preco_mean}')
print(f'desvio de preço: {preco_std}')
print(f'min de preço: {preco_min}')
print(f'Max de preço: {preco_max}')

plt.figure(figsize=(10, 6))
sns.histplot(df['valor_da_fatura'],kde =True )
plt.title('Dados do cliente')
plt.xlabel('Preço')
plt.ylabel('frequencia')
plt.show()

preco_por_suporte = df.groupby('suporte_tecnico')['preco'].agg(['mean','std']).reset_index()
print(preco_por_suporte)

suporte_mais_caros = preco_por_suporte.sort_values (by='mean', ascending=False)
print('suporte com a media mais cara')
print (suporte_mais_caros)

df['suporte_tecnico'] = df['preco']/df['valor_da_fatura']
preco_por_servico = df.groupby('tempo_de_contrato') ['suporte_tecnico'].mean().reset_index()
bairros_mais_valorizados = preco_por_servico.sort_values(by='suporte_tecnico', ascending=False)
print('Precos mais altos por servico')
print(preco_por_servico)

plt.figure(figsize=(7,3.5))
sns.boxplot(x='suporte_tecnico',y='preco', data=df)
plt.title('distribuição estados')
plt.xlabel('suporte_tecnico')
plt.ylabel('preco')
plt.show()