# -*- coding: utf-8 -*-
"""Resumo Texto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EoY2zoNkpGH-wbFB66QyxgUw9Lwe_ztV
"""

# Instalar a biblioteca sumy
!pip install sumy

# Importar as bibliotecas necessárias
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.text_rank import TextRankSummarizer
import nltk

# Baixar os dados necessários para a tokenização
nltk.download('punkt')

# Texto a ser resumido
texto = "A Inteligência Artificial (IA) está se tornando cada vez mais presente em nosso dia a dia, desde smartphones até carros autônomos. Com o objetivo de democratizar o acesso à IA e seus benefícios, o Google AI lançou o Colab, uma plataforma gratuita na nuvem que permite executar código Python em um ambiente com GPU. O Colab oferece uma série de vantagens para desenvolvedores e cientistas de dados, como acesso a um hardware potente sem a necessidade de investimento em infraestrutura própria, além da possibilidade de compartilhar notebooks e colaborar com outros usuários. Além disso, o Colab facilita a instalação de bibliotecas Python e oferece suporte a Jupyter Notebooks, um ambiente interativo para desenvolvimento científico. Se você está interessado em aprender mais sobre IA ou deseja desenvolver seus próprios projetos com machine learning, o Colab é uma excelente ferramenta para começar."

# Criar um objeto TextRankSummarizer
parser = PlaintextParser.from_string(texto, Tokenizer("portuguese"))
summarizer = TextRankSummarizer()

# Gerar o resumo (com 50% do tamanho original)
sentences = summarizer(parser.document, 5)  # Especifica o número de frases no resumo

# Imprimir o resumo
for sentence in sentences:
    print(sentence)