# -*- coding: utf-8 -*-
"""modelo preditivo .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmKMTbu5ShC7bh0g91sImSsEl8x_vdVi
"""

import pandas as pd
import numpy as np
from sklearn.svm import LinearSVC

porco1=[0,1,0] #pelo curto, não faz au-au, rabo curto
porco2=[0,1,1]
porco3=[1,1,0]

cachorro1=[0,1,1] #pelo curto,  faz au-au, rabo longo
cachorro2=[1,0,1]
cachorro3=[1,1,0]

treino_x=[porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
treino_y=[1,1,1,0,0,0]#0-cachorro 1- Porco

modelo=LinearSVC()

modelo.fit(treino_x,treino_y)

animal_misterioso=[1,1,1]
modelo.predict([animal_misterioso])