# -*- coding: utf-8 -*-
"""Cachorro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KskmCJM_u4sTEUbLJ3YFR4SY8fXiDC9
"""

import pandas as pd

import numpy as np

from sklearn.svm import LinearSVC

"""IDENTIFICAR UM PORCO

Características:

- Pelo (pelo curto ou longo)
- Latir (faz "au-au"?)
- Rabo (rabo curto ou longo)

Sempre comparar com algo

0 - tem pelo curto
1 - tem pelo longo

0 - não faz au-au
1 - faz au-au

0 - rabo curto
1 - rabo longo
"""

porco1 = [0,1,0] #pelo curto, não faz au-au, rabo curto
porco2 = [0,1,1]
porco3 = [1,1,0]

"""# Nova seção

# Nova seção
"""

cachorro1 = [0,1,1] #pelo curto, faz au-au, rabo longo
cachorro2 = [1,0,1]
cachorro3 = [1,1,1]

treino_x = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
treino_y = [1,1,1,0,0,0] # 0 - cachorro, 1 - porco

modelo = LinearSVC()

modelo.fit (treino_x, treino_y)

animal_misterioso = [1,1,1]
modelo.predict([animal_misterioso])