# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Importa as bibliotecas necessárias
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Carrega o dataset Iris (dados de flores)
iris = load_iris()

# X = características das flores (tamanho de pétalas e sépalas)
# y = rótulos (tipo da flor: 0, 1 ou 2)
X = iris.data
y = iris.target

#  Divide os dados em treino (80%) e teste (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#  Cria o modelo KNN com 3 vizinhos
modelo = KNeighborsClassifier(n_neighbors=3)

#  Treina o modelo com os dados de treino
modelo.fit(X_train, y_train)

#  Faz previsões usando os dados de teste
previsoes = modelo.predict(X_test)

#  Calcula a acurácia (quantos acertos o modelo teve)
acuracia = accuracy_score(y_test, previsoes)

#  Mostra o resultado final em porcentagem
print(f"A precisão do modelo foi de: {acuracia * 100:.2f}%")

import pandas as pd
from sklearn.linear_model import LinearRegression


df = pd.read_csv('dados_imobiliaria.csv')


X = df[['tamanho_m2']]
y = df['preco_reais']


modelo = LinearRegression()
modelo.fit(X, y)


tamanhos_novos = [[110], [150]]
precos_previstos = modelo.predict(tamanhos_novos)


print(f"Valor para 110m²:R$ {precos_previstos[0]:,.2f}")
print(f"Preço para 150m²:R$ {precos_previstos[1]:,.2f}")