# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install pyTelegramBotAPI pandas scikit-learn

import telebot
import pandas as pd
import logging
logging.basicConfig(level=logging.INFO)
from sklearn.linear_model import LinearRegression



df = pd.read_csv('dados_imobiliaria.csv')

X = df[['tamanho_m2']]
y = df['preco_reais']

modelo = LinearRegression()
modelo.fit(X, y)

print("Modelo treinado com sucesso!")


TOKEN = "8667788897:AAGpWjZSGR1nz6qkkyHiBg-PvoZvAjQu2sc"
bot = telebot.TeleBot(TOKEN)

usuarios={}


@bot.message_handler(commands=['start'])
def boas_vindas(mensagem):
  user_id=mensagem.chat.id
  usuarios[user_id]={"etapa":"tipo"}
  bot.reply_to(
        mensagem,
        " 🤖 Olá! \n"
        "Você procura:\n "
        "🏢 1 - Apartamento\n"
        "🏠 2 - Casa\n"
        "❌ Para sair, digite: sair "
    )


@bot.message_handler(func=lambda mensagem: True)
def fluxo (mensagem):
  user_id=mensagem.chat.id

  if user_id not in usuarios:
    usuarios[user_id]={"etapa": "tipo"}

  etapa = usuarios[user_id]["etapa"]
  texto = mensagem.text.strip().lower()

  if texto == "sair":
    usuarios.pop(user_id, None)
    bot.reply_to(mensagem, "Atendimento cancelado. Digite /start para recomeçar.")
    return

  if etapa == "tipo":
    if texto == "1":
            usuarios[user_id]["tipo"] = "apartamento"
    elif texto == "2":
            usuarios[user_id]["tipo"] = "casa"
    else:
       bot.reply_to (mensagem, "Digite 1 para apartamento ou 2 para casa.")
       return


    usuarios[user_id]["etapa"] = "atendimento"

    bot.reply_to(
             mensagem,
            "Deseja falar com um atendente humano? (sim/nao)"
        )

  elif etapa == "atendimento":
        if texto == "sim":
            bot.reply_to(
                mensagem,
                " Ok! Um atendente humano entrará em contato com você."
            )
            logging.info(f"Usuário {user_id} pediu atendimento humano")
            usuarios.pop(user_id)
            return

        elif texto == "nao":
            usuarios[user_id]["etapa"] = "tamanho"
            bot.reply_to(
                mensagem,
                "Perfeito! Me informe o tamanho do imóvel em m² (ex: 120)"
            )
        else:
            bot.reply_to(mensagem, "Digite 'sim' ou 'nao'.")

  elif etapa == "tamanho":
        try:
            tamanho = float(texto.replace(",", "."))

            if tamanho <= 0:
                bot.reply_to(mensagem, "Digite um valor válido maior que zero.")
                return

            preco = modelo.predict([[tamanho]])[0]
            tipo = usuarios[user_id]["tipo"]

            resposta = (
                f" Tipo: {tipo}\n"
                f" Tamanho: {tamanho:.1f} m²\n"
                f" Preço estimado: R$ {preco:,.2f}"
            )

            bot.reply_to(mensagem, resposta)

            logging.info(f"Previsão feita para {user_id}")
            usuarios.pop(user_id)

        except:
            bot.reply_to(mensagem, "Envie apenas números. Ex: 120")


print(" Bot rodando...")
bot.polling()