# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Nova seção
"""

!pip install pyTelegramBotAPI pandas scikit-learn

import telebot
import pandas as pd
import logging
logging.basicConfig(level=logging.INFO)
from sklearn.linear_model import LinearRegression



df = pd.read_csv('dados_imobiliaria.csv')

X = df[['tamanho_m2']]
y = df['preco_reais']

modelo = LinearRegression()
modelo.fit(X, y)

print("Modelo treinado com sucesso!")


TOKEN = "8667788897:AAGpWjZSGR1nz6qkkyHiBg-PvoZvAjQu2sc"  # coloque seu token do Telegram aqui
bot = telebot.TeleBot(TOKEN)


@bot.message_handler(commands=['start'])
def boas_vindas(mensagem):
    bot.reply_to(
        mensagem,
        "Olá! 👋\n"
        "Me envie o tamanho do imóvel em m² (ex: 120) "
        "e eu te retorno o preço estimado."
    )


@bot.message_handler(func=lambda mensagem: True)
def prever_preco(mensagem):
    try:
        texto = mensagem.text.replace(",", ".")
        tamanho = float(texto)

        if tamanho <= 0:
            bot.reply_to(mensagem, "Digite um valor válido maior que zero.")
            return

        preco_previsto = modelo.predict([[tamanho]])[0]

        resposta = (
            f" Tamanho: {tamanho:.1f} m²\n"
            f" Preço estimado: R$ {preco_previsto:,.2f}"
        )

        bot.reply_to(mensagem, resposta)

    except:
        bot.reply_to(
            mensagem,
            " Envie apenas números.\nExemplo: 120"
        )


print("Bot rodando...")
bot.polling()