# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/tatianecarvalho200/Python-GenAI-Programming/blob/main/Conhe%C3%A7a_o_Colab.ipynb
"""

soma = 0
menor = None
maior = None
quantidade = 0

for i in range(1, 11):
    soma += i
    quantidade += 1


    if menor is None or i < menor:
        menor = i


    if maior is None or i > maior:
        maior = i

media = soma / quantidade #Divido a soma pela quantidade para calcular a media

print(f"Menor: {menor} | Maior: {maior} | Média: {media}")

total_temperatura = 0
quantidade_pessoas = int(input("Quantas pessoas serão analisadas? "))

normais = 0
febris = 0
febre_alta = 0

for i in range(1, quantidade_pessoas + 1): # Ira percorrer a quantidade de pessoas
    print(f"\n Pessoa {i} ")
    temp = float(input("Digite a temperatura: "))

    total_temperatura += temp

    if temp <= 37.2:
        print("Normal")
        normais += 1
    elif 37.3 <= temp <= 38.0:
        print("Febril")
        febris += 1
    elif 38.1 <= temp <= 39.0:
        print("Febre Alta")
        febre_alta += 1
    else:
        print("Fora do padrão")

media = total_temperatura / quantidade_pessoas # Divido o total de temperaturas pela quantidade de pessoas


print(f"RELATÓRIO FINAL")
print(f"Total de pessoas: {quantidade_pessoas}")
print(f"Média das temperaturas: {media:.2f}C")
print(f"Normais: {normais}  Febris: {febris}  Febre Alta: {febre_alta}")



for numero in range(1, 101):
  if numero % 2 == 0:
    print(numero)

notas = 0
notas_alunos = 0

while True:
    nota = float(input("Informe sua nota (-1 para finalizar): "))

    if nota == -1:
        break

    notas = notas + nota
    # Incrementa o contador de alunos
    notas_alunos = notas_alunos + 1

# O cálculo da média fica fora do loop, após o 'break'
if notas_alunos > 0:
    media = notas / notas_alunos
    print(f"\nQuantidade de notas informadas: {notas_alunos}")
    print(f"Média: {media:.2f}")
else:
    print("Nenhuma nota informada.")

soma_homens = soma_mulheres = 0
qtd_homens = qtd_mulheres = 0

total_pessoas = int(input("Quantas pessoas deseja cadastrar? "))

for i in range(total_pessoas):
    print(f" {i+1} PESSOA ")
    sexo = input("Sexo (MASCULINP/FEMININO): ")
    idade = int(input("Idade: "))

    if sexo == 'M':
        soma_homens += idade
        qtd_homens += 1
    elif sexo == 'F':
        soma_mulheres += idade
        qtd_mulheres += 1

media_grupo = (soma_homens + soma_mulheres) / total_pessoas if total_pessoas > 0 else 0
media_homens = soma_homens / qtd_homens if qtd_homens > 0 else 0
media_mulheres = soma_mulheres / qtd_mulheres if qtd_mulheres > 0 else 0



print(f"Média de idade dos HOMENS: {media_homens:.1f}")
print(f"Média de idade das MULHERES: {media_mulheres:.1f}")
print(f"Média de idade do GRUPO: {media_grupo:.1f}")

inicio = 5
fim= 100
print(f"Números entre {inicio} e {fim} divisíveis por 7 e não múltiplos de 5:")

resultados = [] #Para guardar o resultado

for num in range(inicio, fim + 1):
    if num % 7 == 0 and num % 5 != 0:
        resultados.append(num) #O append serve para adicionar um elemento no final em uma lista ja existente
        print(resultados)

texto= str(input("Digite uma palavra para ser lida de tras para frente:  "))
texto_invertido = texto [: : -1] #LER AO CONTRARIO USANDO O NEGATIVO
print(texto_invertido)