# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

def argumento (numero):
  if numero > 0:
    return 'P'
  else:
    return 'N'
teclado = input ("Digite um nuúmero")
valor = float (teclado  )
resultado = argumento(valor)
print(f"O resultado é {resultado}")

def somaImposto (taxaImposto, custo):
    custo_final = custo + (custo*(taxaImposto / 100))
    return custo_final
taxa = float (input("Digite a taxa de imposto:"))
preco = float (input("Digite o custo do item:"))
valor_com_imposto = somaImposto (taxa, preco)
print (f"O valor final com {taxa}% de imposto é:R$ {valor_com_imposto:}")