# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Célula 1
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris # Importa um conjunto de dados pronto (Iris)
from sklearn.model_selection import train_test_split # Função para dividir os dados em treino e teste
from sklearn.neighbors import KNeighborsClassifier # Algoritmo KNN (K-Nearest Neighbors)
from sklearn.metrics import accuracy_score # Função para medir a precisão do modelo

iris = load_iris() # Carrega o dataset Iris (flores)

X = iris.data # X = dados de entrada (características das flores)
y = iris.target # y = saída esperada (qual é a espécie da flor)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
# Divide os dados: 80% para treinar o modelo e 20% para testar se ele aprendeu corretamente

modelo = KNeighborsClassifier(n_neighbors=3) # Cria o modelo KNN com k = 3 (olha os 3 vizinhos mais próximos)
modelo.fit(X_train, y_train) # Treina o modelo com os dados de treino

previsoes = modelo.predict(X_test) # Faz previsões com base nos dados de teste

acuracia = accuracy_score(y_test, previsoes)# Compara previsões com respostas corretas e calcula a precisão (accuracy)

print(f"A precisão do modelo foi de: {acuracia * 100:.2f}%") # Mostra o resultado em porcentagem

# 1. Visualization: Scatter Plot of Petal Length vs Petal Width

plt.figure(figsize=(10, 6)) # Define o tamanho da imagem (largura x altura)

df_test = pd.DataFrame(X_test, columns=iris.feature_names) # Cria um DataFrame (tabela) com os dados de teste
df_test['Espécie Real'] = [iris.target_names[i] for i in y_test] # Adiciona uma coluna com a espécie REAL de cada flor
df_test['Previsão'] = [iris.target_names[i] for i in previsoes] # Adiciona uma coluna com a PREVISÃO do modelo

sns.scatterplot(
    data=df_test,
    x='petal length (cm)',      # eixo X = comprimento da pétala
    y='petal width (cm)',       # eixo Y = largura da pétala
    hue='Espécie Real',         # cor = espécie real
    style='Previsão',           # formato do ponto = previsão
    s=100                       # tamanho dos pontos
)
# Cria o gráfico de dispersão (scatter plot)

plt.title('Comparação: Espécie Real vs Previsão (Pétalas)') # Título do gráfico
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left') # Ajusta a legenda para não ficar em cima do gráfico
plt.tight_layout() # Ajusta automaticamente o espaçamento

plt.savefig('iris_scatter.png') # Salva o gráfico como imagem
plt.show() # Mosra o gráfico
plt.close() # Fecha o gráfico (boa prática para evitar bugs/memória)

from google.colab import files # Importa uma ferramenta do Google Colab que permite interagir com arquivos
files.upload()

import pandas as pd
from sklearn.linear_model import LinearRegression

# 1. Carregar o arquivo
df = pd.read_csv('dados_imobiliaria.csv') # Lê o arquivo CSV e transforma em uma tabela (DataFrame)
X = df[['tamanho_m2']] # X = variável de entrada (tamanho da casa em m²)
y = df['preco_reais'] # y = variável de saída (preço da casa)

# 2. Criar o modelo de regressão linear
modelo = LinearRegression()

# 3. Treinar o modelo
modelo.fit(X, y)

# 4. Fazer previsões
novas_casas = pd.DataFrame({
    'tamanho_m2': [110, 150]
})
# Cria um novo DataFrame com casas que queremos prever

precos_previstos = modelo.predict(novas_casas) # O modelo usa o que aprendeu para prever os preços dessas casas

# 5. Mostrar resultados
for tamanho, preco in zip(novas_casas['tamanho_m2'], precos_previstos):
# Percorre cada tamanho e preço previsto ao mesmo tempo
    print(f"Casa de {tamanho}m² → Preço previsto: R$ {preco:,.2f}")