# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFZeGihdZl84pGIfRPQ_BqHZg-mHrrT7

#exercicio 1 - mostrar numeros pares de 1 a 100
"""

print("Numeros pares de 1 a 100:")

for i in range(1,101):
  if i % 2==0:
     print(i,end='')

"""# exercicio 2 - maior , menor e media de 10 valores"""

maior = None
menor = None
soma = 0

for i in range(10):
  valor=int(input(f"digite o {i+1}° valor inteiro:"))
  soma +=valor

  if maior is None or valor > maior:
    maior = valor
  if menor is None or valor < menor:
    menor = valor

  media = soma/10

  print(f"\nMaior valor:{maior}")
  print(f"Menor valor:{menor}")
  print(f"Media dos valores:{media:.2f}")

"""#analise de temperatura"""

quantidade= int(input("Quantas pessoas deseja analisar?"))
  soma_temperaturas = 0

  for i in range(quantidade):
   temp=float(input(f"digite a temperatura da {i+1}¹pessoa:"))
   soma_temperaturas +=temp

  if temp<37.2:
    print("temperatura normal")
  elif 37.2<=temp<38:
    print("estado febril")
  elif 38<=temp<=39:
    print("com febre")
  else:
    print("com febre alta")

 media=soma_temperaturas/quantidade
 print("\nResumo:")
 print(f"\nQuantidade de pessoas analisadas:{quantidade}")
 print(f"media de temperatura:{media:.2f}°C")