# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QamNWaVXIZ6m6Mdhjkig2aUxVNTeKp-v

#solicita o numero que o usuario quer treinar
"""

numero = int(input("digite o número que deseja treinar na tabuada:"))

acertos = 0
erros = 0

"""#loop de 1 a 10 para perguntar a tabuada"""

for i in range(1,11):
  resposta=int(input(f"{numero}x{i}="))
  resultado_correto=numero*i

  if resposta == resultado_correto:
    print("CORRETO")
    acertos+=1

  else:
      print(f"QUE PENA, VOCÊ ERROU, O VALOR CORRETO É {resultado_correto}")
      erros+=1

"""#resultado final"""

print(f"\nTotal de acertos:{acertos}")
print(f"Total de erros:{erros}")