# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import tensorflow as tf

# CARREGANDO O DATASET MNIST
mnist = tf.keras.datasets.mnist

# separa em treino e teste
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# NORMALIZAÇÃO DOS DADOS
# transforma valores de 0–255 para 0–1
x_train, x_test = x_train / 255.0, x_test / 255.0


# CRIANDO O MODELO
model = tf.keras.models.Sequential([

    # transforma imagem 28x28 em vetor (784 valores)
    tf.keras.layers.Flatten(input_shape=(28, 28)),

    # camada escondida com 128 neurônios
    tf.keras.layers.Dense(128, activation='relu'),

    # desativa 20% dos neurônios aleatoriamente (evita overfitting)
    tf.keras.layers.Dropout(0.2),

    # camada de saída com 10 neurônios (0–9)
    tf.keras.layers.Dense(10, activation='softmax')
])

# COMPILANDO O MODELO
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# TREINANDO O MODELO
model.fit(x_train, y_train, epochs=5)

# AVALIANDO O MODELO
model.evaluate(x_test, y_test)

"""##Teste 1
Foi realizado um teste com uma rede neural simples para classificação de dígitos do dataset MNIST. O modelo utilizou imagens 28x28 normalizadas, uma camada oculta com 128 neurônios, Dropout de 0.2 e saída com 10 classes. O treinamento foi feito por 5 épocas com otimizador Adam e função de perda sparse categorical crossentropy. Como resultado, a IA alcançou **97,5% de acerto** no conjunto de teste, apresentando bom desempenho na tarefa de reconhecimento de números escritos à mão.
"""

import tensorflow as tf

# CARREGANDO O DATASET MNIST
mnist = tf.keras.datasets.mnist

# separa em treino e teste
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# NORMALIZAÇÃO DOS DADOS
# transforma valores de 0–255 para 0–1
x_train, x_test = x_train / 255.0, x_test / 255.0


# CRIANDO O MODELO
model = tf.keras.models.Sequential([

    # transforma imagem 28x28 em vetor (784 valores)
    tf.keras.layers.Flatten(input_shape=(28, 28)),

    # camada escondida com 128 neurônios
    tf.keras.layers.Dense(128, activation='relu'),

    # desativa 20% dos neurônios aleatoriamente (evita overfitting)
    tf.keras.layers.Dropout(0.2),

    # camada de saída com 10 neurônios (0–9)
    tf.keras.layers.Dense(10, activation='softmax')
])

# COMPILANDO O MODELO
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# TREINANDO O MODELO
model.fit(x_train, y_train, epochs=5)

# AVALIANDO O MODELO
model.evaluate(x_test, y_test)

import numpy as np
import matplotlib.pyplot as plt

# faz as previsões do modelo em todas as imagens de teste
predictions = model.predict(x_test)

# pega a classe prevista (o índice com maior valor)
predicted_labels = np.argmax(predictions, axis=1)

# encontra onde o modelo errou
errors = predicted_labels != y_test

# separa as imagens erradas, os rótulos corretos e os previstos
x_errors = x_test[errors]
y_errors = y_test[errors]
pred_errors = predicted_labels[errors]

# mostra quantos erros aconteceram
print("Quantidade de erros:", len(x_errors))

plt.figure(figsize=(12, 8))

for i in range(9):  # mostra 9 erros
    plt.subplot(3, 3, i + 1)
    plt.imshow(x_errors[i], cmap='gray')
    plt.title(f"Correto: {y_errors[i]} | Previsto: {pred_errors[i]}")
    plt.axis('off')

plt.tight_layout()
plt.show()

"""## Teste 2
Dando continuidade ao teste anterior, foi utilizado o mesmo modelo e parâmetros de treinamento aplicados ao dataset MNIST. O modelo manteve evolução consistente, atingindo cerca de **97,7% de acurácia** ao final do treinamento.
Na avaliação com dados de teste, obteve aproximadamente **97,8% de acerto** e loss de **0,0726**, confirmando seu bom desempenho. Como complemento, foi realizada a análise de erros, identificando **217 classificações incorretas** em 10.000 imagen
Esses erros ocorrem, principalmente, em imagens ambíguas ou de difícil interpretação, permitindo uma análise mais aprofundada das limitações do modelo.
"""
