# -*- coding: utf-8 -*-
"""Temp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDr053ZKb-_xqEjWOanCx_VOHLq2UIqd
"""

for numeros in range (1, 101):
  if numeros % 2 == 0:
    print(numeros)

numeros = []

#leitura dos 10 números inteiros
for i in range (10):
  valor = int(input(f"Digite o {i+1}º número: "))
  numeros.append(valor)
  '''.append adiciona os elemenos para a lista'''

maior = max(numeros)
menor = min(numeros)
media = sum(numeros)/len(numeros)
'''sum é a soma dos elemenos, len é a quantidade'''

print(f" Sua lista: {numeros}")
print(f" Maior número: {maior}")
print(f" Menor número: {menor}")
print(f" Média: {media}")

Z = int(input("Quantas pessoas você quer verificar a temperatura? "))
X = []

for i in range(Z):
  temp = float(input(f"Digite a temperatura da {i+1}ª pessoa (ºC): "))
  X.append(temp)

  if temp < 37.2:
    status = "Normal"
  elif 37.3 <= temp < 38:
    status = "Febril"
  elif 38 <= temp <= 39:
    status = "Febre"
  else:
    status = "Febre alta"

  print(f"Temperatura: {temp:}°C - Status: {status}\n")

media = sum(X) / Z

#{.1f} limita a quantidade casa decimais no print para 1
print(f"Quantidade de pessoas analisadas foram {Z} e a média de temperturas é {media:.1f}")