# -*- coding: utf-8 -*-
"""Classificação_Frutas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136Hphqw2rTluLajzqg4E_EWwf8ScCN8I

# Classificando frutas com Machine Learning
###Programação em Inteligência Artificial Generativa
####Prof. Msc. Ailton J. Santos
"""

'''Você trabalha em um supermercado e precisa desenvolver um sistema
automatizado para classificar frutas na esteira rolante.
O sistema precisa ser capaz de identificar diferentes tipos de frutas
com base em suas características visuais, como cor, forma e textura.
Para isso, você decide utilizar o aprendizado de máquina com o
algoritmo de Support Vector Machines (SVM).
Você possui um conjunto de dados de imagens de frutas rotuladas, contendo informações sobre a cor, forma e textura de cada fruta. As características de cada fruta são representadas por um vetor de três elementos:
-------------------
    Cor: Valor numérico que representa a cor principal da fruta
    (por exemplo, 0 para vermelho, 1 para verde, 2 para amarelo).
    Forma: Valor numérico que representa a forma da fruta
    (por exemplo, 0 para redonda, 1 para oval, 2 para irregular).
    Textura: Valor numérico que representa a textura da fruta
    (por exemplo, 0 para lisa, 1 para rugosa, 2 para peluda).
-------------------
Objetivo:

Utilizar o algoritmo SVM para treinar um modelo de classificação de frutas e, em seguida,
usar esse modelo para identificar a categoria de uma nova fruta.

import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC

# Criando listas para armazenar os dados
cores = []
formas = []
texturas = []
categorias = []

# Gerando 100 exemplos de frutas com características e categorias aleatórias
for _ in range(100):
    cores.append(random.randint(0, 2))
    formas.append(random.randint(0, 2))
    texturas.append(random.randint(0, 2))
    categorias.append(random.randint(0, 2))

# Criando um DataFrame
dados_frutas = pd.DataFrame({
    "cor": cores,
    "forma": formas,
    "textura": texturas,
    "categoria": categorias
})

dados_frutas.to_csv("dados_frutas.csv", index=False)

# Carregar dados de frutas
dados_frutas = pd.read_csv('dados_frutas.csv')

# Separar características e rótulos
caracteristicas = dados_frutas[['cor', 'forma', 'textura']]
rotulos = dados_frutas['categoria']

# Dividir dados em treino e teste
X_treino, X_teste, y_treino, y_teste = train_test_split(caracteristicas, rotulos, test_size=0.2, random_state=42)

# Treinar modelo SVM
modelo_svm = LinearSVC()
modelo_svm.fit(X_treino, y_treino)

# Avaliar desempenho do modelo
acuracia = modelo_svm.score(X_teste, y_teste)
print("Acurácia do modelo:", acuracia)

# Classificar uma nova fruta
fruta_nova = [1, 0, 2]  # Cor: verde, Forma: redonda, Textura: peluda
categoria_predita = modelo_svm.predict([fruta_nova])
print("Categoria predita para a nova fruta:", categoria_predita[0])