# -*- coding: utf-8 -*-
"""Fund_Machine_Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0Nq-fGPGc7L2uruFyizim69q1zsHLOu

###Fundamentos de Machine Learning
###Prof. Msc. Ailton J. Santos

### Obtendo fundamentação da Machine Learning

Problema clássico de Machine Learning - Identificando um 🐖 e um 🐕 através de suas características
"""

import pandas as pd
import numpy as np
from sklearn.svm import LinearSVC

"""O scikit-learn é uma biblioteca da linguagem Python desenvolvida especificamente para aplicação prática de machine learning.

Esta biblioteca dispõe de ferramentas simples e eficientes para análise preditiva de dados, é reutilizável em diferentes situações, possui código aberto, sendo acessível a todos e foi construída sobre os pacotes NumPy, SciPy e matplotilib.

O sklearn está organizado em muitos módulos, cada um desenvolvido para uma finalidade específica. Nestes módulos encontraremos funções para as mais diferentes aplicações.

Analisando estas diferentes aplicações entenderemos a organização da biblioteca, e como encontrar o que buscamos.

Pré-processamento – normalmente esta é a etapa mais trabalhosa no desenvolvimento de um modelo de machine learning. Como já vimos, o NumPy e o Pandas são largamente utilizados nesta etapa, mas também teremos funções para esta finalidade no sklearn, pensadas especialmente para tratamento de dados que alimentarão algoritmos de machine learning.
Classificação – desenvolvimento de modelos capazes de detectar a qual categoria pré-determinada um elemento pertence. Podemos identificar se um aluno foi reprovado ou aprovado, se uma pessoa possui ou não determinada doença, ou ainda qual doença uma pessoa pode ter dentre várias possíveis, dentre muitas outras possibilidades.
Regressão – desenvolvimento de modelos que podem atribuir um valor contínuo a um elemento. Podemos prever o preço de um imóvel, altura de uma pessoa, quantidade de vendas de um produto, e assim por diante.
Clusterização – desenvolvimento de modelos para detecção automática de grupos com características similares em seus integrantes. Podemos identificar clientes com comportamentos parecidos, grupos de risco de determinada doença, verificar padrões entre moradores de uma cidade, e muitos outros agrupamentos.
Redução de dimensionalidade – reduzir o número de variáveis em um problema. Com esta redução podemos diminuir consideravelmente a quantidade de cálculos necessários em um modelo, aumentando a eficiência, com uma perde mínima de assertividade.
Ajuste de parâmetros – comparar, validar e escolher parâmetros e modelos, de maneira automatizada. Podemos facilmente comparar diferentes parâmetros no ajuste de um modelo, encontrando assim a melhor configuração para a aplicação em questão.

Fonte: https://scikit-learn.org/stable/
"""

porco1=[0,1,0] # pelo, au-au,rabo
porco2=[0,1,1]
porco3=[1,1,0]

"""Características:

- Pelo (Tem pelo curto ou pelo Longo)
- Latir (Faz "Au-Au?")
- Rabo (Tem rabo curto ou longo?)

Para isso nos baseamos em:

--------------------
0 - Tem pelo curto
1 - Tem pelo longo
--------------------
--------------------
0 - Não faz "Au-Au"
1 - Faz "Au-Au"
--------------------
--------------------
0 - Tem rabo curto
1 - Tem rabo longo
--------------------


"""

cachorro1=[0,1,1]
cachorro2=[1,0,1]
cachorro3=[1,1,1]

treino_x= [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
treino_y = [1,1,1,0,0,0] # 0 cachorro, 1 porco

"""Para isso nos baseamos em:

--------------------
0 - Cachorro
1 - Porco
--------------------
"""

modelo = LinearSVC()

modelo.fit (treino_x, treino_y)

animal_misterioso = [1,1,1]
modelo.predict([animal_misterioso])

