# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CMTnV-CQHF9LZit1g3NXX1Mt3oDoLIyp
"""

import cv2
from google.colab.patches import cv2_imshow
from google.colab import files

# Carrega a imagem
uploaded = files.upload()

# Itera sobre os arquivos enviados
for filename in uploaded.keys():
    # Carrega a imagem
    imagem = cv2.imread(filename)

    # Verifica se a imagem foi carregada corretamente
    if imagem is None:
        print("Error: Image could not be loaded!")
        exit()

    # Converte a imagem para tons de cinza
    imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)

    # Carrega o classificador de face
    classificador_face = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

    # Verifica se o classificador de face foi carregado corretamente
    if classificador_face.empty():
        print("Error: Haarcascade classifier could not be loaded!")
        exit()

    # Detecta faces na imagem
    faces = classificador_face.detectMultiScale(imagem_cinza, 1.1, 4)

    # Desenha retângulos ao redor das faces detectadas
    for (x, y, w, h) in faces:
        cv2.rectangle(imagem, (x, y), (x+w, y+h), (0, 255, 0), 2)

    # Exibe a imagem com as detecções
    cv2_imshow(imagem)