# -*- coding: utf-8 -*-
"""atendimento senai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Kh8Iq8zXEKtEcEK7YW04uvKWl1AUDTI
"""

import pandas as pd
import numpy as np
import random
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

tweets=[]
sentimentos=[]

#Tweet aleatorio
palavras_pos=['maravilhoso', 'incrivel', 'adoro', 'excepcional', 'perfeito']
palavras_neg=['ruim', 'horrivel', 'terriível', 'não recomendo', 'péssimo']
palavras_neu=['bom', 'legal', 'ok', 'interessante', 'informativo']

for _ in range(100):
    #tweet pos, input palavras para classificação positiva
    tweet_pos=random.choice(palavras_pos)+' '+random.choice(palavras_pos)
    tweets.append(tweet_pos)
    sentimentos.append(2)

    #tweet neu, input palavras para classificação neutras
    tweet_neu=random.choice(palavras_neu)+' '+random.choice(palavras_neu)
    tweets.append(tweet_neu)
    sentimentos.append(1)

    #tweet negativo, input palavras para classificação negativa
    tweet_neg=random.choice(palavras_neg)+' '+random.choice(palavras_neg)
    tweets.append(tweet_neg)
    sentimentos.append(0)

#DF
dados_tweet=pd.DataFrame({
    'tweet':tweets,
    'sentimento':sentimentos
})

#DF
dados_tweet.to_csv('dados_tweets.csv', index=False)

dados_tweet=pd.read_csv('dados_tweets.csv')

dados_tweet.head( )

#separação Tweets e Rótulos
tweets=dados_tweet['tweet']
rotulos=dados_tweet['sentimento']

#Conversão dos tweets em vetores
vectorizer=TfidfVectorizer()
tweets_vetorizados=vectorizer.fit_transform(tweets)

#Treino em X e Y
x_treino, x_teste, y_treino, y_teste=train_test_split(tweets_vetorizados, rotulos, test_size=0.2, random_state=42)

#Equalização (Treino) Naives Bayes
modelo=MultinomialNB()
modelo.fit(x_treino, y_treino)

#Avaliação de desempenho do modelo(Acurácia)
acuracia=modelo.score(x_teste, y_teste)
print('Acurácia do modelo é:', acuracia)

#classificação dos Tweets (predição)
tweet_novo = 'Amei o novo produto da marca! #maravilhoso'
vetor_novo = vectorizer.transform([tweet_novo])
sentimento_predito = modelo.predict(vetor_novo)
print('O sentimento do novo tweet é:', sentimento_predito[0])