# -*- coding: utf-8 -*-
"""eduardo_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXCw-wXX_OCZl4PvBIgpbt4Su43VfJ8g
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Gerar alguns dados fictícios: idade e altura (em cm)
# Supondo que a relação é aproximadamente linear
np.random.seed(42)  # Para reprodutibilidade
idade = np.random.randint(1, 20, 50)
altura = 50 + 6 * idade + np.random.randn(50) * 3

# Dividir os dados em conjunto de treino e teste
idade_treino, idade_teste, altura_treino, altura_teste = train_test_split(idade, altura, test_size=0.2, random_state=42)

# Reshape necessário para o sklearn
idade_treino = idade_treino.reshape(-1, 1)
idade_teste = idade_teste.reshape(-1, 1)

# Criar o modelo de Regressão Linear
modelo = LinearRegression()

# Treinar o modelo
modelo.fit(idade_treino, altura_treino)

# Fazer previsões
altura_predita = modelo.predict(idade_teste)

# Avaliar o modelo
erro_medio_quadratico = mean_squared_error(altura_teste, altura_predita)
print(f'Erro Médio Quadrático: {erro_medio_quadratico:.2f}')

# Prever a altura de uma nova idade
nova_idade = np.array([[10]])
altura_prevista = modelo.predict(nova_idade)
print(f'A altura prevista para uma pessoa de {nova_idade[0][0]} anos é: {altura_prevista[0]:.2f} cm')